# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8cb5afccba23caa41bea5073442698dab86b3e957fffb17fd959274d18bbcec9cccb6310ef41202907827d9ca334b3f1310537327a204aa38cffbbc7734cbfe
  fb_access_token: CAADFZAIL8xY8BABOZBX2POEIk3C8kNmqXDuOGAAMKoAwg8CAGXvC2JNfNNAKX58b4g7JYZCWHgCl940BPiuzBXZBuqj92TFn7hHwDfrZB1XsZBnM34BOj5RcFwrVL5RaXiRBkUraT3ZAmijBDUOMoH9c2bk40ve5EytOzZB3ZAWPx44ZCIdyhvL66x9qshCR9xpD8PKZCMXiuX8aj0La4HRlbP7

test:
  secret_key_base: 5a24c51a1de2b998efded3b0fa8e60b777252c58cbaced823c30b131f3789c5af729f44536aefb62a6d55e47398d8fc81fb86348c64698bcbb2588073a6c7f9e
  fb_access_token: CAADFZAIL8xY8BAN0osZAX4oNu8YpeLkaudDSo6AfgV80ZC8QpaaoWSiiO6vGflxZBbT9nuMwGTmadlU7lj6o1YJBR0p0UlykFhSXYhFWmXVQAZC1bbYrwIZAc6eZBgDJ7C8H2ZC7n8GrVABYREcdlQNmuJtxX66cWkl5XpxHeqVvcznaeCW106U7HvtDVsbZAwMeCcBThDUk40KS1xJMAzsKT

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
